In [1]:
import numpy as np

In [2]:
l = ["ajay" , 1,2,3,4]

In [3]:
type(l)

list

In [4]:
type(np.array(l))

numpy.ndarray

In [5]:
np.array(l)

array(['ajay', '1', '2', '3', '4'], dtype='<U11')

In [7]:
a1 = np.array([3,4,5,6,3.0])
a1

array([3., 4., 5., 6., 3.])

In [8]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
np.array([[1,2,3],[2,3,4]])[1][1]

3

## Dimansions 

In [10]:
a2 = np.array([1,2,3,4],ndmin = 4)

In [11]:
a2

array([[[[1, 2, 3, 4]]]])

In [13]:
a2[0][0][0][0]

1

## Array Functions

In [14]:
l=[1,2,3,4]

In [15]:
np.array(l)

array([1, 2, 3, 4])

In [16]:
np.asarray(l)

array([1, 2, 3, 4])

In [17]:
np.asanyarray(l)

array([1, 2, 3, 4])

## Matrix

In [18]:
l=[1,2,3,4]

In [19]:
np.mat(l)

matrix([[1, 2, 3, 4]])

In [20]:
np.asanyarray(np.mat(l))

matrix([[1, 2, 3, 4]])

## FromFunction

In [22]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j,k : i+j+k,(5,3,3),dtype=int)

#Simple Explaination - 5 arrays of 3x3

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]],

       [[3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]],

       [[4, 5, 6],
        [5, 6, 7],
        [6, 7, 8]]])

In [29]:
np.fromfunction(lambda i,j,k,l : i+j+k+l,(5,4,3,3),dtype=int)

#Simple Explaination - 4 arrays of 3x3, with 5 combinations(repetition)

array([[[[ 0,  1,  2],
         [ 1,  2,  3],
         [ 2,  3,  4]],

        [[ 1,  2,  3],
         [ 2,  3,  4],
         [ 3,  4,  5]],

        [[ 2,  3,  4],
         [ 3,  4,  5],
         [ 4,  5,  6]],

        [[ 3,  4,  5],
         [ 4,  5,  6],
         [ 5,  6,  7]]],


       [[[ 1,  2,  3],
         [ 2,  3,  4],
         [ 3,  4,  5]],

        [[ 2,  3,  4],
         [ 3,  4,  5],
         [ 4,  5,  6]],

        [[ 3,  4,  5],
         [ 4,  5,  6],
         [ 5,  6,  7]],

        [[ 4,  5,  6],
         [ 5,  6,  7],
         [ 6,  7,  8]]],


       [[[ 2,  3,  4],
         [ 3,  4,  5],
         [ 4,  5,  6]],

        [[ 3,  4,  5],
         [ 4,  5,  6],
         [ 5,  6,  7]],

        [[ 4,  5,  6],
         [ 5,  6,  7],
         [ 6,  7,  8]],

        [[ 5,  6,  7],
         [ 6,  7,  8],
         [ 7,  8,  9]]],


       [[[ 3,  4,  5],
         [ 4,  5,  6],
         [ 5,  6,  7]],

        [[ 4,  5,  6],
         [ 5,  6,  7],
         [ 6,  7,  8]],



In [30]:
a=np.fromfunction(lambda i,j,k,l : i+j+k+l,(5,4,3,3),dtype=int)

In [31]:
a.ndim

4

In [32]:
a.size

180

In [33]:
a.shape

(5, 4, 3, 3)

In [34]:
a.dtype

dtype('int32')

## Random Data

In [35]:
np.random.rand(10,4)

array([[0.9151246 , 0.12773075, 0.66705784, 0.05728718],
       [0.29013007, 0.79407128, 0.87345629, 0.41024347],
       [0.8728978 , 0.51459621, 0.94027159, 0.73733886],
       [0.80460698, 0.06797793, 0.22316713, 0.81194957],
       [0.57122703, 0.65235295, 0.82434073, 0.16588883],
       [0.93336489, 0.30287188, 0.10352892, 0.6680432 ],
       [0.77655822, 0.99935013, 0.73185962, 0.70248822],
       [0.63273187, 0.88400337, 0.09680558, 0.88921505],
       [0.93124076, 0.10424992, 0.23920197, 0.20341898],
       [0.56676166, 0.69524117, 0.90993196, 0.54437193]])

In [37]:
np.random.randint(4,50)

20

In [38]:
np.random.randn(4,5)
#gives random normally distributed

array([[ 0.23285326, -0.07951384, -1.07460191, -1.79142449, -0.12940291],
       [-1.04071345,  1.63034474,  0.29052307, -0.35744707, -0.45663964],
       [-0.24305337, -0.66089467, -0.64672566,  0.2981644 , -0.3387249 ],
       [-0.87082409, -0.98018224,  0.21835047,  0.97983484, -0.60917739]])

## Reshape Array to 2D

In [39]:
a=np.fromfunction(lambda i,j,k,l : i+j+k+l,(5,4,3,3),dtype=int)

In [42]:
a.reshape(18,10)
#2D
#Rows x Col should be equal to size of array

array([[ 0,  1,  2,  1,  2,  3,  2,  3,  4,  1],
       [ 2,  3,  2,  3,  4,  3,  4,  5,  2,  3],
       [ 4,  3,  4,  5,  4,  5,  6,  3,  4,  5],
       [ 4,  5,  6,  5,  6,  7,  1,  2,  3,  2],
       [ 3,  4,  3,  4,  5,  2,  3,  4,  3,  4],
       [ 5,  4,  5,  6,  3,  4,  5,  4,  5,  6],
       [ 5,  6,  7,  4,  5,  6,  5,  6,  7,  6],
       [ 7,  8,  2,  3,  4,  3,  4,  5,  4,  5],
       [ 6,  3,  4,  5,  4,  5,  6,  5,  6,  7],
       [ 4,  5,  6,  5,  6,  7,  6,  7,  8,  5],
       [ 6,  7,  6,  7,  8,  7,  8,  9,  3,  4],
       [ 5,  4,  5,  6,  5,  6,  7,  4,  5,  6],
       [ 5,  6,  7,  6,  7,  8,  5,  6,  7,  6],
       [ 7,  8,  7,  8,  9,  6,  7,  8,  7,  8],
       [ 9,  8,  9, 10,  4,  5,  6,  5,  6,  7],
       [ 6,  7,  8,  5,  6,  7,  6,  7,  8,  7],
       [ 8,  9,  6,  7,  8,  7,  8,  9,  8,  9],
       [10,  7,  8,  9,  8,  9, 10,  9, 10, 11]])

In [44]:
a.reshape(9,2,10)
#3D
#a x b x c  should be equal to size of array

array([[[ 0,  1,  2,  1,  2,  3,  2,  3,  4,  1],
        [ 2,  3,  2,  3,  4,  3,  4,  5,  2,  3]],

       [[ 4,  3,  4,  5,  4,  5,  6,  3,  4,  5],
        [ 4,  5,  6,  5,  6,  7,  1,  2,  3,  2]],

       [[ 3,  4,  3,  4,  5,  2,  3,  4,  3,  4],
        [ 5,  4,  5,  6,  3,  4,  5,  4,  5,  6]],

       [[ 5,  6,  7,  4,  5,  6,  5,  6,  7,  6],
        [ 7,  8,  2,  3,  4,  3,  4,  5,  4,  5]],

       [[ 6,  3,  4,  5,  4,  5,  6,  5,  6,  7],
        [ 4,  5,  6,  5,  6,  7,  6,  7,  8,  5]],

       [[ 6,  7,  6,  7,  8,  7,  8,  9,  3,  4],
        [ 5,  4,  5,  6,  5,  6,  7,  4,  5,  6]],

       [[ 5,  6,  7,  6,  7,  8,  5,  6,  7,  6],
        [ 7,  8,  7,  8,  9,  6,  7,  8,  7,  8]],

       [[ 9,  8,  9, 10,  4,  5,  6,  5,  6,  7],
        [ 6,  7,  8,  5,  6,  7,  6,  7,  8,  7]],

       [[ 8,  9,  6,  7,  8,  7,  8,  9,  8,  9],
        [10,  7,  8,  9,  8,  9, 10,  9, 10, 11]]])

In [45]:
a.reshape(9,-1)
# -1 automatically manage multiple of 9

array([[ 0,  1,  2,  1,  2,  3,  2,  3,  4,  1,  2,  3,  2,  3,  4,  3,
         4,  5,  2,  3],
       [ 4,  3,  4,  5,  4,  5,  6,  3,  4,  5,  4,  5,  6,  5,  6,  7,
         1,  2,  3,  2],
       [ 3,  4,  3,  4,  5,  2,  3,  4,  3,  4,  5,  4,  5,  6,  3,  4,
         5,  4,  5,  6],
       [ 5,  6,  7,  4,  5,  6,  5,  6,  7,  6,  7,  8,  2,  3,  4,  3,
         4,  5,  4,  5],
       [ 6,  3,  4,  5,  4,  5,  6,  5,  6,  7,  4,  5,  6,  5,  6,  7,
         6,  7,  8,  5],
       [ 6,  7,  6,  7,  8,  7,  8,  9,  3,  4,  5,  4,  5,  6,  5,  6,
         7,  4,  5,  6],
       [ 5,  6,  7,  6,  7,  8,  5,  6,  7,  6,  7,  8,  7,  8,  9,  6,
         7,  8,  7,  8],
       [ 9,  8,  9, 10,  4,  5,  6,  5,  6,  7,  6,  7,  8,  5,  6,  7,
         6,  7,  8,  7],
       [ 8,  9,  6,  7,  8,  7,  8,  9,  8,  9, 10,  7,  8,  9,  8,  9,
        10,  9, 10, 11]])

## Range

In [46]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [49]:
list(range(4,10,2))

[4, 6, 8]

In [54]:
a1 = np.arange(4,10,.2)
a1

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [55]:
a1[1:4]

array([4.2, 4.4, 4.6])

## Misc

In [56]:
arr = np.random.rand(4,5)

In [57]:
arr[arr>.5]

array([0.58586432, 0.76130574, 0.57475885, 0.63614094, 0.78740087,
       0.9316148 , 0.94023982, 0.85555315, 0.5017183 , 0.92595911,
       0.79756302])

In [58]:
arr

array([[0.58586432, 0.16184564, 0.76130574, 0.57475885, 0.19501418],
       [0.63614094, 0.43369954, 0.22026689, 0.78740087, 0.9316148 ],
       [0.38325843, 0.11644419, 0.94023982, 0.40718463, 0.85555315],
       [0.02888781, 0.5017183 , 0.92595911, 0.38547926, 0.79756302]])

In [59]:
arr[[1,2] , [2]]

array([0.22026689, 0.94023982])

In [71]:
arr = np.random.rand(8,5)
arr

array([[0.59884888, 0.48538124, 0.87634647, 0.4347135 , 0.55494017],
       [0.26075755, 0.52993476, 0.32345488, 0.75820746, 0.75728259],
       [0.47353387, 0.23218529, 0.68670968, 0.93524201, 0.07211961],
       [0.41986014, 0.22955624, 0.57057249, 0.11714885, 0.72381948],
       [0.13792981, 0.48741463, 0.48359545, 0.64016531, 0.00142543],
       [0.85078076, 0.15244778, 0.39992974, 0.92734316, 0.49196284],
       [0.47463295, 0.51328109, 0.79447312, 0.15447723, 0.87608696],
       [0.50566029, 0.55503977, 0.8697737 , 0.55367165, 0.30183794]])

In [72]:
arr[1:8 , 0:3]

array([[0.26075755, 0.52993476, 0.32345488],
       [0.47353387, 0.23218529, 0.68670968],
       [0.41986014, 0.22955624, 0.57057249],
       [0.13792981, 0.48741463, 0.48359545],
       [0.85078076, 0.15244778, 0.39992974],
       [0.47463295, 0.51328109, 0.79447312],
       [0.50566029, 0.55503977, 0.8697737 ]])

In [73]:
arr[0][0] = 100

In [74]:
arr

array([[1.00000000e+02, 4.85381241e-01, 8.76346469e-01, 4.34713501e-01,
        5.54940172e-01],
       [2.60757549e-01, 5.29934758e-01, 3.23454883e-01, 7.58207463e-01,
        7.57282588e-01],
       [4.73533874e-01, 2.32185295e-01, 6.86709681e-01, 9.35242007e-01,
        7.21196118e-02],
       [4.19860136e-01, 2.29556241e-01, 5.70572492e-01, 1.17148852e-01,
        7.23819481e-01],
       [1.37929811e-01, 4.87414630e-01, 4.83595446e-01, 6.40165313e-01,
        1.42542941e-03],
       [8.50780761e-01, 1.52447781e-01, 3.99929737e-01, 9.27343164e-01,
        4.91962837e-01],
       [4.74632954e-01, 5.13281088e-01, 7.94473121e-01, 1.54477231e-01,
        8.76086961e-01],
       [5.05660292e-01, 5.55039769e-01, 8.69773695e-01, 5.53671654e-01,
        3.01837942e-01]])

## Matrix Element Mutiplication

In [75]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [76]:
a*b

array([[ 2,  6],
       [12, 20]])

## Matrix Multiplication

In [77]:
a@b

array([[10, 13],
       [22, 29]])

## Division by Zero on NumPy is Infinity

In [78]:
a/0

C:\Users\eraja\AppData\Local\Temp/ipykernel_9508/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf],
       [inf, inf]])

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [10]:
np.empty((2,4))

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 6.66e-321, 0.00e+000, 0.00e+000]])

In [12]:
np.empty(4)

array([1., 1., 1., 1.])

In [17]:
#Generate 10 numbers b/w 2 to 6
#without 3rd parameter i.e. 10 it will consider it as 50
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [19]:
#Ignore the upperbound value i.e. 6
np.linspace(2,6,10,endpoint=False)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6])

In [20]:
#Setp Size
np.linspace(2,6,10,endpoint=False,retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [23]:
np.logspace(2,6,10,base=2)

array([ 4.        ,  5.44316   ,  7.4069977 , 10.0793684 , 13.71590373,
       18.66446463, 25.39841683, 34.56191164, 47.03150375, 64.        ])

In [30]:
a= np.arange(4,20).reshape(4,4)
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
a.max()

19

In [33]:
a= np.arange(4,40).reshape(3,6,2)
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [34]:
a.max()

39

In [35]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [36]:
a.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [37]:
a= np.arange(4,40).reshape(6,6)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [38]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [39]:
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [40]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

### Operations

In [41]:
10+a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [42]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [44]:
pow(a,4)

array([[    256,     625,    1296,    2401,    4096,    6561],
       [  10000,   14641,   20736,   28561,   38416,   50625],
       [  65536,   83521,  104976,  130321,  160000,  194481],
       [ 234256,  279841,  331776,  390625,  456976,  531441],
       [ 614656,  707281,  810000,  923521, 1048576, 1185921],
       [1336336, 1500625, 1679616, 1874161, 2085136, 2313441]],
      dtype=int32)

In [48]:
b=np.array([2,3,5,2,1,3])

In [52]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [50]:
#Row wise broadcasting
a+b

array([[ 6,  8, 11,  9,  9, 12],
       [12, 14, 17, 15, 15, 18],
       [18, 20, 23, 21, 21, 24],
       [24, 26, 29, 27, 27, 30],
       [30, 32, 35, 33, 33, 36],
       [36, 38, 41, 39, 39, 42]])

In [51]:
#Column wise broadcasting
a+b.reshape(1,-1).T

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26],
       [24, 25, 26, 27, 28, 29],
       [29, 30, 31, 32, 33, 34],
       [37, 38, 39, 40, 41, 42]])

In [54]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [56]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [57]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

### Deep Copy vs Shallow Copy

In [73]:
x=np.array([1,2,3])
y=x
#Shallow Copy

In [74]:
x

array([1, 2, 3])

In [75]:
y

array([1, 2, 3])

In [76]:
# Deep Copy
z=np.copy(x)

In [77]:
z

array([1, 2, 3])

In [78]:
x[0]=100

In [79]:
y

array([100,   2,   3])

In [80]:
x

array([100,   2,   3])

In [81]:
z

array([1, 2, 3])

In [82]:
id(x)

2602930034320

In [83]:
id(y)

2602930034320

In [84]:
id(z)

2602930034800

In [101]:
z=250
v=2501

if id(z) == id(v) :
    print('same')
else:
    print('different')

different
